trigger:
- none  # Manual trigger only for now

pool:
  name: Default  # This tells Azure DevOps to use your self-hosted agent in the Default pool

steps:
- script: echo "✅ Running on Chioma's Self-Hosted Agent!"
  displayName: 'Print success message'

- task: AzureCLI@2
  displayName: 'Test Azure CLI connection'
  inputs:
    azureSubscription: 'cadd-devops'  # Replace with your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "✅ Connected to Azure"
      az account show
      az group list --output table
