trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - k8s-specifications/*.yaml  # Prevent retrigger from YAML auto-commit

variables:
  IMAGE_TAG: $[variables['Build.BuildId']]
  REPO_PATH: 'k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default  # Use your self-hosted agent pool

stages:

  # ---------------------- #
  #  Stage 1: Build & Push #
  # ---------------------- #
  - stage: BuildAndPush
    displayName: "Build and Push Docker Images"
    jobs:
      - job: BuildImages
        displayName: "Build Docker Images"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: "Build and Push 'vote'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'vote/Dockerfile'
              buildContext: 'vote'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Build and Push 'result'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'result/Dockerfile'
              buildContext: 'result'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Build and Push 'worker'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'worker/Dockerfile'
              buildContext: 'worker'
              tags: |
                $(IMAGE_TAG)
                latest

  # ---------------------------- #
  #  Stage 2: Update Manifests   #
  # ---------------------------- #
  - stage: UpdateManifests
    displayName: "Update K8s Manifests & Push"
    dependsOn: BuildAndPush
    jobs:
      - job: UpdateYaml
        displayName: "Update Image Tags and Commit"
        steps:
          - checkout: self

          - script: |
              echo "Updating image tags to :$(IMAGE_TAG)"
              sed -i "s#chiomaacr
