- stage: BuildAndPush
  dependsOn: CloneMicroservicesRepo
  jobs:
    - job: DockerBuildPush
      pool:
        name: 'Default'
      steps:
        - checkout: self

        - download: current
          artifact: MicroservicesRepo

        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: 'login'
            containerRegistry: 'online-boutique'

        - script: |
            echo "✅ Starting Docker Build & Push for Microservices..."
            cd MicroservicesRepo/src
            for service in *; do
              if [ -d "$service" ] && [ -f "$service/Dockerfile" ]; then
                echo "🚀 Building and Pushing $service ..."
                docker build -t chiomaacr.azurecr.io/$service:latest $service
                docker push chiomaacr.azurecr.io/$service:latest
              else
                echo "⚠️ Skipping $service - Dockerfile not found."
              fi
            done
          displayName: 'Build & Push Microservices'
