resources:
  repositories:
    - repository: voting-app
      type: github
      name: chiomanwanedo/example-voting-app
      endpoint: github.com_chiomanwanedo

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - k8s-specifications/*.yaml

variables:
  IMAGE_TAG: $[variables['Build.BuildId']]
  REPO_PATH: 'k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default

stages:

  # ---------------------- #
  #  Stage 1: Build & Push #
  # ---------------------- #
  - stage: BuildAndPush
    displayName: "Build and Push Docker Images"
    jobs:
      - job: BuildImages
        steps:
          - checkout: self
          - checkout: voting-app
            path: example-voting-app

          - script: |
              echo "Verifying vote Dockerfile exists:"
              ls -al example-voting-app/vote
            displayName: "Debug Dockerfile Path"

          - task: Docker@2
            displayName: "Build and Push 'vote'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'example-voting-app/vote/Dockerfile'
              buildContext: 'example-voting-app/vote'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "
