trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: votingapp
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo  # <-- This must match your GitHub service connection name

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote + result
        pool:
          name: Default  # <-- Your self-hosted agent pool name
        steps:
          - checkout: votingapp
            path: app  # This puts your GitHub repo in a folder named "app"

          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'  # Your ACR service connection name
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'app/vote/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'result' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'app/result/Dockerfile'
              tags: |
                $(IMAGE_TAG)
