trigger:
  branches:
    include:
      - main

stages:
  - stage: CloneAndTest
    jobs:
      - job: CloneJob
        pool:
          name: 'Default'
        steps:
          - checkout: self  # Checkout your agent repo

          - script: |
              echo "✅ Cloning microservices-demo repo (Repo B)..."
              git clone https://github.com/chiomanwanedo/microservices-demo.git
            displayName: 'Clone Microservices Repo'

          - script: |
              echo "✅ Successfully cloned! Listing contents:"
              ls -l microservices-demo
            displayName: 'List Cloned Repo Content'

  - stage: BuildAndPush
    dependsOn: CloneAndTest
    jobs:
      - job: DockerBuild
        pool:
          name: 'Default'
        steps:
          - checkout: self  # Still required for agent context

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'  # Your service connection name to ACR

          - script: |
              cd microservices-demo/src
              for service in *; do
                if [ -f "$service/Dockerfile" ]; then
                  echo "🔨 Building $service..."
                  docker build -t chiomaacr.azurecr.io/$service:latest $service
                  echo "🚀 Pushing $service to ACR..."
                  docker push chiomaacr.azurecr.io/$service:latest
                else
                  echo "⚠️ No Dockerfile found for $service, skipping."
                fi
              done
            displayName: 'Build & Push Microservices'
