trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: votingapp
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo  # <-- Replace with your actual GitHub service connection name

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default  # <-- Your self-hosted agent pool name
        steps:
          - checkout: votingapp
            path: .

          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'vote/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'result' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'result/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'worker' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'worker/Dockerfile'
              tags: |
                $(IMAGE_TAG)
