trigger:
  branches:
    include:
      - main

variables:
  IMAGE_TAG: $[variables['Build.BuildId']]
  REPO_PATH: 'k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default  # Use your self-hosted agent pool

stages:

  # ---------------------- #
  #  Stage 1: Build & Push #
  # ---------------------- #
  - stage: BuildAndPush
    displayName: "Build and Push Docker Images"
    jobs:
      - job: BuildImages
        displayName: "Build Docker Images"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: "Build and Push 'vote'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'vote/Dockerfile'
              buildContext: 'vote'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: "Build and Push 'result'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'result/Dockerfile'
              buildContext: 'result'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: "Build and Push 'worker'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'worker/Dockerfile'
              buildContext: 'worker'
              tags: |
                $(IMAGE_TAG)

  # ---------------------------- #
  #  Stage 2: Update Manifests   #
  # ---------------------------- #
  - stage: UpdateManifests
    displayName: "Update K8s Manifests & Push"
    dependsOn: BuildAndPush
    jobs:
      - job: UpdateYaml
        displayName: "Update Image Tags and Commit"
        steps:
          - checkout: self

          - script: |
              echo "Updating image tags to :$(IMAGE_TAG)"
              sed -i "s#chiomaacr.azurecr.io/vote:.*#chiomaacr.azurecr.io/vote:$(IMAGE_TAG)#g" $REPO_PATH/$VOTE_FILE
              sed -i "s#chiomaacr.azurecr.io/result:.*#chiomaacr.azurecr.io/result:$(IMAGE_TAG)#g" $REPO_PATH/$RESULT_FILE
              sed -i "s#chiomaacr.azurecr.io/worker:.*#chiomaacr.azurecr.io/worker:$(IMAGE_TAG)#g" $REPO_PATH/$WORKER_FILE

              echo "Showing manifest diff:"
              git diff
            displayName: "Update Image Tags in YAML Files"

          - script: |
              git config user.email "chiomavanessa8@gmail.com"
              git config user.name "chiomanwanedo"
              git add $REPO_PATH/*.yaml
              git commit -m "Update image tags to :$(IMAGE_TAG) [skip ci]" || echo "No changes to commit"
              git push origin main
            displayName: "Commit and Push Updated YAML Files"

  # ---------------------------- #
  #  Stage 3: Deploy to Cluster  #
  # ---------------------------- #
  - stage: DeployToK8s
    displayName: "Deploy Updated YAMLs to Kubernetes"
    dependsOn: UpdateManifests
    jobs:
      - job: DeployK8s
        displayName: "Apply Kubernetes Manifests"
        steps:
          - checkout: self

          - script: |
              mkdir -p ~/.kube
              echo "$(KUBECONFIG_CONTENT)" > ~/.kube/config
              chmod 600 ~/.kube/config
            displayName: "Set Up Kubeconfig"

          - script: |
              kubectl apply -f $REPO_PATH/$VOTE_FILE
              kubectl apply -f $REPO_PATH/$RESULT_FILE
              kubectl apply -f $REPO_PATH/$WORKER_FILE
            displayName: 'Apply Updated Manifests to Cluster'
