---
name: vote-pipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: app_code
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github
      trigger:
        branches:
          include:
            - main
        paths:
          include:
            - example-voting-app/vote/**

variables:
  imageName: vote
  tag: $(Build.BuildId)
  dockerRegistryServiceConnection: dockeracr
  containerRegistry: chiomaacr.azurecr.io
  gitUsername: $(GITHUB_USERNAME)
  gitToken: $(GITHUB_TOKEN)

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        pool:
          name: Default
        steps:
          - checkout: app_code

          - script: |
              echo "🔍 Checking Dockerfile..."
              ls -l "$(Build.SourcesDirectory)/app_code/example-voting-app/vote/Dockerfile"
            displayName: Debug: Check Dockerfile

          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: "$(Build.SourcesDirectory)/app_code/example-voting-app/vote/Dockerfile"
              tags: |
                $(tag)

  - stage: UpdateK8sYaml
    dependsOn: BuildAndPush
    jobs:
      - job: PatchYAML
        pool:
          name: Default
        steps:
          - task: Bash@3
            displayName: Patch vote-deployment.yaml
            inputs:
              targetType: inline
              script: |
                git config --global user.email "chiomavanessa8@gmail.com"
                git config --global user.name "$(gitUsername)"

                echo "🔁 Cloning k8s-specifications repo..."
                git clone https://$(gitUsername):$(gitToken)@github.com/chiomanwanedo/k8s-specifications.git
                cd k8s-specifications

                echo "🛠️ Updating vote-deployment.yaml..."
                sed -i "s|image: .*/vote:.*|image: $(containerRegistry)/vote:$(tag)|" vote-deployment.yaml

                git add vote-deployment.yaml
                git commit -m "Update vote image to :$(tag) [skip ci]"
                git push
