resources:
  repositories:
    - repository: voting-app
      type: github
      name: chiomanwanedo/example-voting-app
      endpoint: github  # Replace with your actual service connection if different

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - k8s-specifications/*.yaml

variables:
  IMAGE_TAG: $[variables['Build.BuildId']]
  REPO_PATH: 'k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default

stages:

  # -------------------------------------- #
  #  Stage 1: Build and Push Docker Images #
  # -------------------------------------- #
  - stage: BuildAndPush
    displayName: "Build and Push Docker Images"
    condition: succeeded()
    jobs:
      - job: BuildImages
        steps:
          - checkout: self
          - checkout: voting-app
            path: voting-app

          - script:
