trigger:
  branches:
    include:
      - main

stages:
  - stage: CloneAndBuild
    jobs:
      - job: CloneJob
        pool:
          name: 'Default'
        steps:
          - checkout: self  # Checkout the agent repo (Repo A)

          - script: |
              echo "✅ Cloning microservices-demo repo (Repo B) with retry and shallow clone..."
              git config --global http.postBuffer 524288000  # Increase buffer size to handle large repo
              for i in {1..3}; do
                git clone --depth=1 https://github.com/chiomanwanedo/microservices-demo.git && break || {
                  echo "⚠️ Clone failed. Retrying in 10 seconds... ($i/3)"
                  sleep 10
                }
              done
            displayName: 'Clone Microservices Repo with Retry'

          - script: |
              echo "✅ Successfully cloned! Listing contents:"
              ls -l microservices-demo
            displayName: 'List Cloned Repo Content'
