trigger:
  branches:
    include:
      - main

variables:
  IMAGE_TAG: $[variables['Build.BuildId']]
  REPO_PATH: 'voting-app/k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Images"
    jobs:
      - job: BuildImages
        steps:
          - checkout: self  # Checkout the myagent repo (where this pipeline lives)

          - checkout: voting-app  # Checkout the app repo
            path: voting-app

          - task: Docker@2
            displayName: "Build and Push 'vote'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'voting-app/vote/Dockerfile'
              buildContext: 'voting-app/vote'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Build and Push 'result'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'voting-app/result/Dockerfile'
              buildContext: 'voting-app/result'
              tags: |
                $(IMAGE_TAG)
                latest

          - task: Docker@2
            displayName: "Build and Push 'worker'"
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'voting-app/worker/Dockerfile'
              buildContext: 'voting-app/worker'
              tags: |
                $(IMAGE_TAG)
                latest

  - stage: UpdateManifests
    displayName: "Update K8s Manifests & Push"
    dependsOn: BuildAndPush
    jobs:
      - job: UpdateYaml
        steps:
          - checkout: self
          - checkout: voting-app

          - script: |
              echo "Updating image tags to :$(IMAGE_TAG)"
              sed -i "s#chiomaacr.azurecr.io/vote:.*#chiomaacr.azurecr.io/vote:$(IMAGE_TAG)#g" $REPO_PATH/$VOTE_FILE
              sed -i "s#chiomaacr.azurecr.io/result:.*#chiomaacr.azurecr.io/result:$(IMAGE_TAG)#g" $REPO_PATH/$RESULT_FILE
              sed -i "s#chiomaacr.azurecr.io/worker:.*#chiomaacr.azurecr.io/worker:$(IMAGE_TAG)#g" $REPO_PATH/$WORKER_FILE

              echo "Showing manifest diff:"
              git -C voting-app diff
            displayName: "Update Image Tags in YAML Files"

          - script: |
              git -C voting-app config user.email "chiomavanessa8@gmail.com"
              git -C voting-app config user.name "chiomanwanedo"
              git -C voting-app add k8s-specifications/*.yaml
              git -C voting-app commit -m "Update image tags to :$(IMAGE_TAG) [skip ci]" || echo "No changes to commit"
              git -C voting-app push origin main
            displayName: "Commit and Push Updated YAML Files"

  - stage: DeployToK8s
    displayName: "Deploy to Kubernetes"
    dependsOn: UpdateManifests
    jobs:
      - job: DeployK8s
        steps:
          - checkout: self
          - checkout: voting-app

          - script: |
              mkdir -p ~/.kube
              echo "$(KUBECONFIG_CONTENT)" > ~/.kube/config
              chmod 600 ~/.kube/config
            displayName: "Set Up Kubeconfig"

          - script: |
              for f in $REPO_PATH/$VOTE_FILE $REPO_PATH/$RESULT_FILE $REPO_PATH/$WORKER_FILE; do
                echo "Applying $f"
                kubectl apply -f $f || { echo "Retrying $f"; sleep 5; kubectl apply -f $f; }
              done
            displayName: "Deploy to Cluster"
