trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: apprepo
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default  # Replace with your actual agent pool name
        steps:
          - checkout: apprepo
            path: app
