trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: apprepo
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default  # Replace with your self-hosted agent pool name if needed
        steps:
          - checkout: apprepo
            path: app  # ✅ Prevents double nesting like app/app/vote

          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'app/vote/Dockerfile'
              buildContext: 'app/vote'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'result' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'app/result/Dockerfile'
              buildContext: 'app/result'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'worker' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'app/worker/Dockerfile'
              buildContext: 'app/worker'
              tags: |
                $(IMAGE_TAG)
