trigger:
  branches:
    include:
      - main

stages:
  - stage: CloneAndTest
    jobs:
      - job: CloneJob
        pool:
          name: 'Default'
        steps:
          - checkout: self

          - script: |
              echo "✅ Cloning microservices-demo repo (Repo B)..."
              git clone https://github.com/chiomanwanedo/microservices-demo.git
            displayName: 'Clone Microservices Repo'

          - publish: microservices-demo
            artifact: microservices-repo

  - stage: BuildAndPush
    dependsOn: CloneAndTest
    jobs:
      - job: DockerBuild
        pool:
          name: 'Default'
        steps:
          - checkout: self

          - download: current
            artifact: microservices-repo

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'online-boutique'

          - script: |
              cd $(Pipeline.Workspace)/microservices-repo/src
              for service in *; do
                if [ -f "$service/Dockerfile" ]; then
                  echo "🔨 Building $service..."
                  docker build -t chiomaacr.azurecr.io/$service:latest $service
                  echo "🚀 Pushing $service to ACR..."
                  docker push chiomaacr.azurecr.io/$service:latest
                else
                  echo "⚠️ No Dockerfile found for $service, skipping."
                fi
              done
            displayName: 'Build & Push Microservices'
