---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - example-voting-app/vote/**
      - example-voting-app/k8s-specifications/vote-deployment.yaml

name: vote-pipeline-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: app_code
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github
      trigger:
        branches:
          include:
            - main
        paths:
          include:
            - example-voting-app/vote/**
            - example-voting-app/k8s-specifications/**

variables:
  imageName: vote
  tag: $(Build.BuildId)
  containerRegistry: chiomaacr.azurecr.io
  gitUsername: $(GITHUB_USERNAME)
  gitToken: $(GITHUB_TOKEN)

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        pool:
          name: Default
        steps:
          - checkout: app_code

          - task: Bash@3
            displayName: "Debug:Check Dockerfile"
            inputs:
              targetType: inline
              script: |
                echo "🔍 Checking Dockerfile location..."
                ls -l "$(Build.SourcesDirectory)/app_code/example-voting-app/vote/Dockerfile"

          - task: Bash@3
            displayName: "📁 Tree: Show folder structure"
            inputs:
              targetType: inline
              script: |
                echo "📁 Showing structure under $(Build.SourcesDirectory)/app_code"
                find "$(Build.SourcesDirectory)/app_code" -type f      

          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              containerRegistry: dockeracr
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: "$(Build.SourcesDirectory)/app_code/example-voting-app/vote/Dockerfile"
              tags: |
                $(tag)

  - stage: UpdateK8sYaml
    dependsOn: BuildAndPush
    jobs:
      - job: PatchYAML
        pool:
          name: Default
        steps:
          - task: Bash@3
            displayName: "Patch vote-deployment.yaml"
            inputs:
              targetType: inline
              script: |
                cd "$(Build.SourcesDirectory)/app_code/example-voting-app/k8s-specifications"

                echo "🛠️ Updating vote-deployment.yaml..."
                sed -i "s|image: .*/vote:.*|image: $(containerRegistry)/vote:$(tag)|" vote-deployment.yaml

                git config --global user.email "chiomavanessa8@gmail.com"
                git config --global user.name "$(gitUsername)"

                git add vote-deployment.yaml
                git commit -m "Update vote image to :$(tag) [skip ci]"
                git push
