---
trigger:
  branches:
    include:
      - main

name: vote-pipeline-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  imageName: vote
  tag: $(Build.BuildId)
  containerRegistry: chiomaacr.azurecr.io
  gitUsername: $(GITHUB_USERNAME)
  gitToken: $(GITHUB_TOKEN)

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        pool:
          name: Default
        steps:
          - checkout: self

          - task: Bash@3
            displayName: "🔁 Clone example-voting-app repo"
            inputs:
              targetType: inline
              script: |
                echo "🔐 Cloning app repo..."
                git clone https://$(gitUsername):$(gitToken)@github.com/chiomanwanedo/example-voting-app.git

          - task: Bash@3
            displayName: "📁 Tree: Show structure of cloned repo"
            inputs:
              targetType: inline
              script: |
                echo "📁 Contents of cloned app repo:"
                find example-voting-app -type f

          - task: Bash@3
            displayName: "🔍 Check Dockerfile location"
            inputs:
              targetType: inline
              script: |
                ls -l example-voting-app/vote/Dockerfile

          - task: Docker@2
            displayName: "🐳 Build and Push Docker image"
            inputs:
              containerRegistry: dockeracr
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: "$(Build.SourcesDirectory)/example-voting-app/vote/Dockerfile"
              tags: |
                $(tag)

  - stage: UpdateK8sYaml
    dependsOn: BuildAndPush
    jobs:
    - job: PatchYAML
      pool:
        name: Default
      steps:
        - checkout: self

        - task: Bash@3
          displayName: "🐛 Debug: Check vote-deployment.yaml exists"
          inputs:
            targetType: inline
            script: |
              echo "🔍 Checking for k8s-specifications directory..."
              ls -la example-voting-app/k8s-specifications || echo "❌ Directory not found"

              echo "🔍 Checking for vote-deployment.yaml..."
              ls -l example-voting-app/k8s-specifications/vote-deployment.yaml || echo "❌ File not found"

        - task: Bash@3
          displayName: "🛠️ Patch vote-deployment.yaml"
          inputs:
            targetType: inline
            script: |
              cd example-voting-app/k8s-specifications

              echo "🔧 Updating image tag..."
              sed -i "s|image: .*/vote:.*|image: $(containerRegistry)/vote:$(tag)|" vote-deployment.yaml

              git config --global user.email "chiomavanessa8@gmail.com"
              git config --global user.name "chiomanwanedo"

              git add vote-deployment.yaml
              git commit -m "Update vote image to :$(tag) [skip ci]" || echo "✅ No changes to commit"
              git push origin HEAD:main
