trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: apprepo              # ✅ local alias (used in 'checkout')
      type: github
      name: chiomanwanedo/example-voting-app  # ✅ actual GitHub repo
      ref: main
      endpoint: github.com_chiomanwanedo     # ✅ GitHub service connection name

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default  # ✅ Replace with your self-hosted agent pool if needed
        steps:
          - checkout: apprepo
            path: fetched-app  # ✅ Final unique folder name to avoid nesting

          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'  # ✅ Your ACR service connection
              repository: 'vote'
