trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: apprepo  # local alias
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo  # your GitHub service connection

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default  # or your custom self-hosted agent pool name
        steps:
          - checkout: apprepo
            path: example-voting-app  # ✅ avoid same name as repo to prevent nesting

          - task: Docker@2
            displayName: Build and
