- stage: BuildAndPush
  dependsOn: CloneMicroservicesRepo
  jobs:
    - job: DockerBuildPush
      pool:
        name: 'Default'
      steps:
        - checkout: self
        - download: current
          artifact: MicroservicesRepo

        - script: |
            if [ ! -d "$(Pipeline.Workspace)/MicroservicesRepo/src" ]; then
              echo "❌ Artifact missing or empty!"
              exit 1
            fi
          displayName: 'Verify Artifact Exists'

        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: 'login'
            containerRegistry: 'online-boutique'

        - script: |
            echo "✅ Starting Docker Build & Push for Microservices..."
            cd $(Pipeline.Workspace)/MicroservicesRepo/src
            for service in *; do
              if [ -d "$service" ] && [ -f "$service/Dockerfile" ]; then
                echo "🚀 Building and Pushing $service ..."
                docker build -t $(acrName)/$service:latest $service
                docker push $(acrName)/$service:latest
              else
                echo "⚠️ Skipping $service - Dockerfile not found."
              fi
            done
          displayName: 'Build & Push Microservices'
