---
name: result-pipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - result/**
      - k8s-specifications/result-deployment.yaml

variables:
  imageName: result
  tag: $(Build.BuildId)
  containerRegistry: chiomaacr.azurecr.io
  gitUsername: $(GITHUB_USERNAME)
  gitToken: $(GITHUB_TOKEN)

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        pool:
          name: Default
        steps:
          - checkout: self

          - task: Bash@3
            displayName: "🔁 Clone example-voting-app repo"
            inputs:
              targetType: inline
              script: |
                git clone https://$(gitUsername):$(gitToken)@github.com/chiomanwanedo/example-voting-app.git

          - task: Bash@3
            displayName: "🔍 Check Dockerfile location"
            inputs:
              targetType: inline
              script: |
                echo "🔍 Checking Dockerfile for result service..."
                ls -l example-voting-app/result/Dockerfile

          - task: Docker@2
            displayName: "🐳 Build and Push Docker image for result"
            inputs:
              containerRegistry: dockeracr
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: "$(Build.SourcesDirectory)/example-voting-app/result/Dockerfile"
              tags: |
                $(tag)

  - stage: PatchK8sYAML
    dependsOn: BuildAndPush
    jobs:
      - job: PatchYAML
        pool:
          name: Default
        steps:
          - checkout: self

          - task: Bash@3
            displayName: "📥 Clone app repo again for patching"
            inputs:
              targetType: inline
              script: |
                git clone https://$(gitUsername):$(gitToken)@github.com/chiomanwanedo/example-voting-app.git

          - task: Bash@3
            displayName: "🛠️ Patch result-deployment.yaml"
            inputs:
              targetType: inline
              script: |
                cd example-voting-app/k8s-specifications

                echo "🔧 Updating image tag for result..."
                sed -i "s|image: .*/result:.*|image: $(containerRegistry)/result:$(tag)|" result-deployment.yaml

                git config --global user.email "chiomavanessa8@gmail.com"
                git config --global user.name "chiomanwanedo"

                git add result-deployment.yaml
                git commit -m "Update result image to :$(tag) [skip ci]" || echo "✅ No changes to commit"
                git push https://$(gitUsername):$(gitToken)@github.com/chiomanwanedo/example-voting-app.git HEAD:main
