trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: votingapp
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default
        steps:
          # ✅ Checkout the GitHub repo into a wrapper folder
          - checkout: votingapp
            path: checkout-folder

          # ✅ Build and push 'vote' image
          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'checkout-folder/example-voting-app/vote/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          # ✅ Build and push 'result' image
          - task: Docker@2
            displayName: Build and Push 'result' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'checkout-folder/example-voting-app/result/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          # ✅ Build and push 'worker' image
          - task: Docker@2
            displayName: Build and Push 'worker' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'checkout-folder/example-voting-app/worker/Dockerfile'
              tags: |
                $(IMAGE_TAG)
