trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: votingapp
      type: github
      name: chiomanwanedo/example-voting-app
      ref: main
      endpoint: github.com_chiomanwanedo
      name: apprepo  # 👈 forces the inner folder to be named "apprepo"

variables:
  IMAGE_TAG: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    jobs:
      - job: PushImages
        displayName: Build & Push vote, result, and worker
        pool:
          name: Default
        steps:
          - checkout: apprepo
            path: fetched-app  # ✅ doesn't match anything else

          - task: Docker@2
            displayName: Build and Push 'vote' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'fetched-app/vote/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'result' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'fetched-app/result/Dockerfile'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'worker' image
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'fetched-app/worker/Dockerfile'
              tags: |
                $(IMAGE_TAG)
