trigger:
  branches:
    include:
      - main

variables:
  IMAGE_TAG: $(Build.BuildId)
  REPO_PATH: 'k8s-specifications'
  VOTE_FILE: 'vote-deployment.yaml'
  RESULT_FILE: 'result-deployment.yaml'
  WORKER_FILE: 'worker-deployment.yaml'

pool:
  name: Default  # Your self-hosted agent pool

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: BuildImages
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push 'vote'
            inputs:
              containerRegistry: 'dockeracr'  # ACR service connection name
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'vote/Dockerfile'
              buildContext: 'vote'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'result'
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'result/Dockerfile'
              buildContext: 'result'
              tags: |
                $(IMAGE_TAG)

          - task: Docker@2
            displayName: Build and Push 'worker'
            inputs:
              containerRegistry: 'dockeracr'
              repository: 'worker'
              command: 'buildAndPush'
              Dockerfile: 'worker/Dockerfile'
              buildContext: 'worker'
              tags: |
                $(IMAGE_TAG)

  - stage: UpdateManifests
    displayName: Update K8s Manifests & Push
    dependsOn: BuildAndPush
    jobs:
      - job: UpdateYaml
        steps:
          - checkout: self

          - script: |
              echo "Updating image tags to :$(IMAGE_TAG)"
              sed -i "s#chiomaacr.azurecr.io/vote:.*#chiomaacr.azurecr.io/vote:$(IMAGE_TAG)#g" $REPO_PATH/$VOTE_FILE
              sed -i "s#chiomaacr.azurecr.io/result:.*#chiomaacr.azurecr.io/result:$(IMAGE_TAG)#g" $REPO_PATH/$RESULT_FILE
              sed -i "s#chiomaacr.azurecr.io/worker:.*#chiomaacr.azurecr.io/worker:$(IMAGE_TAG)#g" $REPO_PATH/$WORKER_FILE

              echo "Showing manifest diff:"
              git diff
            displayName: "Update Image Tags in Manifests"

          - script: |
              git config user.email "chiomavanessa8@gmail.com"
              git config user.name "chiomanwanedo"
              git add $REPO_PATH/*.yaml
              git commit -m "Update image tags to :$(IMAGE_TAG) [ci skip]" || echo "No changes to commit"
              git push origin main
            displayName: "Commit and Push Changes"
