resources:
  repositories:
  - repository: app_repo
    type: github
    name: chiomanwanedo/microservices-demo
    endpoint: online-boutique  # ✅ Azure DevOps GitHub Service Connection name

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrLoginServer: chiomaacr.azurecr.io
  acrName: chiomaacr
  imageTag: $(Build.BuildId)

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Images'
  jobs:
  - job: BuildPush
    steps:
    - checkout: self  # ✅ This checks out sample_test (agent repo)
    - checkout: app_repo  # ✅ Check out the application repo (microservices-demo)

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'chiomaacr'  # ✅ Azure DevOps Service Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)
          services=("adservice" "checkoutservice" "shippingservice")
          for service in "${services[@]}"; do
            echo "🔨 Building $service..."
            docker build -t $(acrLoginServer)/$service:$(imageTag) $(Build.SourcesDirectory)/microservices-demo/src/$service
            echo "🚀 Pushing $service..."
            docker push $(acrLoginServer)/$service:$(imageTag)
          done

- stage: UpdateManifestsAndDeploy
  displayName: 'Update Manifests and Deploy via GitOps'
  dependsOn: BuildAndPush
  jobs:
  - job: UpdateManifests
    steps:
    - checkout: self
    - checkout: app_repo
      persistCredentials: true
      clean: true

    - script: |
        services=("adservice" "checkoutservice" "shippingservice")
        for service in "${services[@]}"; do
          file="$(Build.SourcesDirectory)/microservices-demo/kubernetes-manifests/$service.yaml"
          if [[ -f "$file" ]]; then
            echo "✅ Updating $service manifest..."
            sed -i "s|image: $(acrLoginServer)/$service:.*|image: $(acrLoginServer)/$service:$(imageTag)|" "$file"
            echo "# Deployed on $(date -u)" >> "$file"
          fi
        done
      displayName: 'Update Kubernetes Manifests with New Image Tags'

    - script: |
        cd $(Build.SourcesDirectory)/microservices-demo
        branch=$(git rev-parse --abbrev-ref HEAD)
        if [[ "$branch" == "HEAD" ]]; then
          git checkout main || git checkout -b main
          branch="main"
        fi
        git config user.name "chiomanwanedo"
        git config user.email "chiomavanessa8@gmail.com"
        git add kubernetes-manifests/*.yaml
        if git diff --cached --quiet; then
          echo "✅ No manifest changes to commit."
        else
          git commit -m "✅ Updated manifests with new image tags $(imageTag)"
          git push origin $branch
        fi
      displayName: 'Commit and Push Manifest Changes'
