trigger: none

resources:
  repositories:
    - repository: voting-app
      type: github
      name: chiomanwanedo/example-voting-app   # ✅ Must match your GitHub repo
      endpoint: github       # ✅ Your GitHub service connection

pool:
  name: Default  # Your self-hosted agent pool

jobs:
  - job: VerifyGitHubRepoCheckout
    displayName: "Test Checkout of GitHub Repo"
    steps:
      - checkout: self
      - checkout: voting-app
        path: example-voting-app

      - script: |
          echo "✅ Verifying contents of GitHub repo:"
          ls -l example-voting-app
        displayName: "List GitHub App Repo Contents"
